

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    container_name: backend-app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-app
    restart: unless-stopped
    depends_on:
      - backend
